name: Release Docker images
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build-and-push:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Login to Docker
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: make docker-build docker-push DOCKER_REPO=docker.pkg.github.com/$GITHUB_REPOSITORY
